### ISSUE TITLE
[Victory] Prioritizing issues discussion

### ISSUE THREAD

**Issue by saman** [eMoflon/emoflon-victory#14]
Regarding prioritize issues that we talked in sprint overview, I think we can give issue votes with emoji reactions in GitHub.

I added thumbs up and thumbs down.

What do you think?

**Comment by LegionaryCohort** [comment]
It seems to me that this issue is never actually used for the purpose of discussing priorities.
We tend to do that during the monthly Sprint presentations.

I recommend we close this to remove unnecessary clutter.

**Comment by anthonyanjorin** [comment]
Well - which issues are planned in the near future (for the next sprint)?  Perhaps we should discuss in this thread what we want to work on (or start working on) and what not?  This is bound to get more and more important as our time runs out.
