### ISSUE TITLE
[Extra Exit Options] Add "restart" as an alternative to "quit"

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-victory#17]
Would be nice to make the current quit button also a dropdown with further options.  At the moment I can think of a restart that simply closes the window (kills everything), and restarts the same application from scratch, opening a new window.

**Comment by LegionaryCohort** [comment]
Any thoughts on this?
Should we just leave it the way it is now, or should we invest some time into making this more thread-safe?

**Comment by anthonyanjorin** [comment]
I don't really see the concrete added value of this.  Improvement only on demand is my motto :)

**Comment by LegionaryCohort** [comment]
Allright, closing this issue then.
Should the need arise, we can always open a new issue.
