### ISSUE TITLE
[Victory] Improvements concerning protocol steps to make them more informative

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-victory#19]
The following improvements concerning protocol steps should be considered:
1) Rename the Protocol Step #x to Rule Application #x.
2) Provide a tooltip on each Protocol Step (#x), which displays the rule name that was applied in the particular step.

**Comment by LegionaryCohort** [comment]
This issue is superceded by Issue #30 
The UI feature has been implemented but still needs to be fed with data from the Core side.
