### ISSUE TITLE
[Victory] Differentiate rules already applied from rules with no match 

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-victory#21]
Especially concerning FWD/BWD once a match is applied, the rule can't be differentiated from rules that never had a match. As it can be seen in the screenshot below, once the rulePackage2Aadlpackage is applied it's visualized the same as the other rules that never had any match. 
This isn't a big problem in modelgen. Although I suggest a consistent way(for modelgen, FWD/BWD) of differentiating between all "rules already applied" and "rules with no match" should be adopted. This can probably be done by displaying rule names in different shades.
![Screen Shot 2019-08-09 at 2 06 35 PM](https://user-images.githubusercontent.com/43295444/62778276-4370ff00-bab0-11e9-8964-cd1dc67a7873.png)
![Screen Shot 2019-08-09 at 2 06 43 PM](https://user-images.githubusercontent.com/43295444/62778280-453ac280-bab0-11e9-8782-0b417675d803.png)

**Comment by 09Ankita** [comment]
Merged with stable branch.
