### ISSUE TITLE
[Victory] UI freezes when open user options menu is selected......

### ISSUE THREAD

**Issue by Ayurshi** [eMoflon/emoflon-victory#22]
....with no match being selected at the very start of Victory debugger.
Ideally, at the very start when no match has been selected this option button should be disabled. 
![Screen Shot 2019-08-19 at 11 32 04 AM](https://user-images.githubusercontent.com/43295444/63255022-191ffe00-c275-11e9-9614-724f13926138.png)

**Comment by Ayurshi** [comment]
Possibly also consider renaming this button as User Options.

**Comment by LegionaryCohort** [comment]
Please test to see if this issue persist after the migration.

**Comment by Ayurshi** [comment]
Yes, the issue still exists.

**Comment by LegionaryCohort** [comment]
I've managed to locate and fix a bug that appears to match your description.
