### ISSUE TITLE
[Victory] Highlighting Protocol steps for a certain rule

### ISSUE THREAD

**Issue by Surbhi2111** [eMoflon/emoflon-victory#23]
Highlighting the protocol steps for a certain rule lets say UserNetworkBridgeRule as in the image, when the rule is selected or choosen as it can help visualise the models with the help of Protocol steps.
![2019-08-19](https://user-images.githubusercontent.com/45486012/63259006-99e2f800-c27d-11e9-8309-d036017b3e93.png)

**Comment by LegionaryCohort** [comment]
Duplicate of issue #3
