### ISSUE TITLE
[Victory] Suggestion for having the "Restart" feature as a button

### ISSUE THREAD

**Issue by daryazarkalam** [eMoflon/emoflon-victory#26]
In order to use the Restart feature, the user has to tick the "Restart" checkbox and then click on the "Quit Debugger" button which can be a bit confusing. I suggest having two separate buttons "Restart" and "Quit" as conventionally used in most operating systems (Shutdown and Restart in Windows for instance).

**Comment by 09Ankita** [comment]
Merged with stable branch.
