### ISSUE TITLE
[Victory] Restart feature not working.

### ISSUE THREAD

**Issue by Surbhi2111** [eMoflon/emoflon-victory#29]
When I tried restarting the debugger by clicking the RESTART button the debbuger quits but never restarts..  And I am getting the following exception in the console..
![2019-09-23](https://user-images.githubusercontent.com/45486012/65463070-5fa9df00-de57-11e9-8bd5-edb225ef90f1.png)

**Comment by LegionaryCohort** [comment]
The problem has been fixed and the changes merged into the stable branch.
