### ISSUE TITLE
[Victory]Rule name not provided for Protocol steps.

### ISSUE THREAD

**Issue by Surbhi2111** [eMoflon/emoflon-victory#30]
The debugger isnt displaying the rule name for Protocol steps .. but is showing "Rule name not provided"

![2019-09-23 (1)](https://user-images.githubusercontent.com/45486012/65463444-ff676d00-de57-11e9-9f7f-784ad23f49b4.png)

**Comment by JaneJose** [comment]
This is an enhancement that was implemented in the last Sprint. "Rule name not provided" is just a place holder. Once core merges their changes the actual rule name will be displayed.

**Comment by anthonyanjorin** [comment]
Ok - then please assign this to core.  In any case the issue should be kept open until it is fixed and in a release.

**Comment by LegionaryCohort** [comment]
The necessary changes have been merged into the stable branches.
