### ISSUE TITLE
Ugly +, - buttons :(

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-victory#33]
Sorry to bring this up again, but the +, - (collapse, expand) buttons are hideous.

Either put them back beside the Apply button (still terrible but better than how they are at the moment), or put them as actions in a context menu (right-click on the rule view), or find out how to add a real context menu for SWT views.

**Comment by JaneJose** [comment]
Feature implemented as items in a context menu and merged to stable branch.
