### ISSUE TITLE
[UI] Design of the user option control panel 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-victory#7]
The current mix of checkboxes and dropdown looked a bit ugly for me :(

How about using checkboxes for everything, and adding parents/children for cases where there are the same "sub-options"?  I.e., something like this (the sub-options could actually be radio buttons as they are exclusive):

- Corr Labels
    [ ] Full
    [ ] Abbreviated
    [ ] Hide

We could also make the top-option a checkbox and remove the sub-option (hide) -- so not checking the checkbox would equate to hiding the labels.

What do you think?

**Comment by 09Ankita** [comment]
Merged with stable branch.
